"""initial schema

Revision ID: 23d8758cb419
Revises: 
Create Date: 2026-07-26 21:50:45.256393
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '23d8758cb419'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('request_ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operation_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operation_logs_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_logs_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_operation_logs_user_id'), ['user_id'], unique=False)

    op.create_table('network_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('device_name', sa.String(length=150), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('building', sa.String(length=100), nullable=True),
    sa.Column('room', sa.String(length=100), nullable=True),
    sa.Column('vlan', sa.String(length=50), nullable=True),
    sa.Column('switch_name', sa.String(length=100), nullable=True),
    sa.Column('switch_port', sa.String(length=100), nullable=True),
    sa.Column('account_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('registered_at', sa.Date(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('network_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_network_assets_ip_address'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_network_assets_mac_address'), ['mac_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_network_assets_user_name'), ['user_name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('real_name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('account_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_no', sa.String(length=30), nullable=False),
    sa.Column('batch_name', sa.String(length=200), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('applicant_department', sa.String(length=100), nullable=True),
    sa.Column('applicant', sa.String(length=100), nullable=True),
    sa.Column('application_date', sa.Date(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('pending_count', sa.Integer(), nullable=False),
    sa.Column('handler', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('result_file_id', sa.Integer(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_batches_batch_no'), ['batch_no'], unique=True)

    op.create_table('attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_type', sa.String(length=50), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_business_type'), ['business_type'], unique=False)

    op.create_table('maintenance_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_no', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('requester', sa.String(length=100), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('problem_description', sa.Text(), nullable=True),
    sa.Column('handling_process', sa.Text(), nullable=True),
    sa.Column('fault_cause', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('handler', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_records_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_records_record_no'), ['record_no'], unique=True)

    op.create_table('meeting_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_no', sa.String(length=30), nullable=False),
    sa.Column('meeting_name', sa.String(length=200), nullable=False),
    sa.Column('meeting_time', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('technicians', sa.String(length=300), nullable=True),
    sa.Column('equipment', sa.Text(), nullable=True),
    sa.Column('debug_content', sa.Text(), nullable=True),
    sa.Column('problem_description', sa.Text(), nullable=True),
    sa.Column('handling_process', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('onsite_support', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meeting_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_records_record_no'), ['record_no'], unique=True)

    op.create_table('network_asset_histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('change_reason', sa.String(length=300), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['network_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('network_asset_histories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_network_asset_histories_asset_id'), ['asset_id'], unique=False)

    op.create_table('account_batch_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('real_name', sa.String(length=100), nullable=True),
    sa.Column('identity_no', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('account_name', sa.String(length=100), nullable=True),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('permission_type', sa.String(length=50), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('result', sa.String(length=30), nullable=False),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['account_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'account_name', name='uq_batch_account')
    )
    with op.batch_alter_table('account_batch_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_batch_items_batch_id'), ['batch_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_batch_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_batch_items_batch_id'))

    op.drop_table('account_batch_items')
    with op.batch_alter_table('network_asset_histories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_network_asset_histories_asset_id'))

    op.drop_table('network_asset_histories')
    with op.batch_alter_table('meeting_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_records_record_no'))

    op.drop_table('meeting_records')
    with op.batch_alter_table('maintenance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_records_record_no'))
        batch_op.drop_index(batch_op.f('ix_maintenance_records_category'))

    op.drop_table('maintenance_records')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_business_type'))
        batch_op.drop_index(batch_op.f('ix_attachments_business_id'))

    op.drop_table('attachments')
    with op.batch_alter_table('account_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_batches_batch_no'))

    op.drop_table('account_batches')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('network_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_network_assets_user_name'))
        batch_op.drop_index(batch_op.f('ix_network_assets_mac_address'))
        batch_op.drop_index(batch_op.f('ix_network_assets_ip_address'))

    op.drop_table('network_assets')
    with op.batch_alter_table('operation_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operation_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_operation_logs_module'))
        batch_op.drop_index(batch_op.f('ix_operation_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_operation_logs_business_id'))

    op.drop_table('operation_logs')
    op.drop_table('departments')
    # ### end Alembic commands ###
